### ISSUE TITLE
Cambio Vistas Entidad Cliente (Prueba)

### ISSUE THREAD

**Issue by MssBabs** [MssBabs/MelitBurguer#12]
Sustuir Formulario (div{})

//////////
<div class="container" *ngIf="clientes">
        <div class="row cols-sm=1 cols-md=2 cols-lg=2 cols-xl=2 no-gutters mb-3">
            <div class="col p-1" *ngFor="let cliente of clientes ;trackBy: trackId">
                <div class="card-body no-body">
                    <p><a [routerLink]="['/cliente', cliente.id, 'view' ]">{{cliente.id}}</a></p>
                    <p>{{cliente.nombre}}</p>
                    <p>{{cliente.apellido}}</p>
                    <p>{{cliente.telefono}}</p>
                    <p>{{cliente.correo}}</p>
                    <p>{{cliente.puntos}}</p>
                    <p class="btn-group">
                        <button type="submit"
                                [routerLink]="['/cliente', cliente.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/cliente', cliente.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'cliente', { outlets: { popup: cliente.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </p>
                </div>
            </div>
        </div>
    </div>
//////////

**Comment by MssBabs** [comment]
///////////
<div class="container" *ngIf="clientes">
        <div class="row cols-sm=1 cols-md=2 cols-lg=2 cols-xl=2 no-gutters mb-3">
            <div class="col p-1" *ngFor="let cliente of clientes ;trackBy: trackId">
                <div class="card-body no-body">
                    <p><a [routerLink]="['/cliente', cliente.id, 'view' ]">{{cliente.id}}</a></p>
                    <p>{{cliente.nombre}}</p>
                    <p>{{cliente.apellido}}</p>
                    <p>{{cliente.telefono}}</p>
                    <p>{{cliente.correo}}</p>
                    <p>{{cliente.puntos}}</p>
                    <p class="btn-group">
                        <button type="submit"
                                [routerLink]="['/cliente', cliente.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/cliente', cliente.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'cliente', { outlets: { popup: cliente.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </p>
                </div>
            </div>
        </div>
    </div>

**Comment by MssBabs** [comment]
falta actualizar los datos en la vista componet tras cerrar modal editar

**Comment by DanielDominguezR** [comment]
actualizado la recarga de datos, faltaria hacer el merge
